### ISSUE TITLE
Scales other than 4x?

### ISSUE THREAD

**Issue by dawnmew** [StarArawn/bevy_tiled#15]
Hello!

I really, really, really want to use this library, but it seems to be hard-coded to a 4x scale? Is there really no way to change that...? I want something more like 1x or 2x for my project, and it seems like a very strange omission...

**Comment by martinfiers** [comment]
The 4x scale seems to be encoded in src/tile_map.vert:

```vec3 position = Vertex_Position * vec3(4.0, 4.0, 1.0);```

Changing it there seems to do the trick. But I'm not sure what would be the best way to make it configurable (so you don't have to modify the vertex shader). 

Modifying the camera position doesn't seem to work properly.

In my use case I actually would like to performing zooming in/out (mouse scroll). So a configurable scale would be nice!

**Comment by MichaelFroelich** [comment]
Hey guys

I found out how to do this and I've added it to the examples here: https://github.com/StarArawn/bevy_tiled/pull/21

Next I'll figure out how to retrigger the render pipeline so we can get some rotation, this is especially important for iso tiles because otherwise things can get hidden behind the map

**Comment by martinfiers** [comment]
Looks great, I gave a small remark on the PR.
